version: "3.9"

services:
  face_recognition:
    container_name: face_recognition
    build: ./django_app
    command: ./start.sh
    ports:
      - "8005:8000"
    depends_on:
        - db
    env_file: .env
    

  db:
    image: postgres:15
    container_name: fr_db
    hostname: fr_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=face_recognition
  
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080

volumes:
  postgres_data: